import { useState } from "react";
import { SymbolMark } from "./SymbolMark";

const gallery = [
  { label: "Photorealistic", grad: "from-orange-400 via-pink-500 to-violet-700" },
  { label: "Digital art", grad: "from-cyan-300 via-violet-500 to-fuchsia-700" },
  { label: "Fantasy", grad: "from-emerald-300 via-teal-500 to-indigo-800" },
  { label: "Product", grad: "from-zinc-200 via-zinc-500 to-zinc-900" },
  { label: "Branding", grad: "from-amber-300 via-rose-500 to-purple-800" },
  { label: "Illustration", grad: "from-sky-300 via-blue-500 to-indigo-900" },
  { label: "Logo", grad: "from-fuchsia-300 via-violet-500 to-violet-900" },
  { label: "Concept", grad: "from-lime-300 via-emerald-500 to-cyan-900" },
];

const prompts = [
  "A neon koi swimming through cosmic clouds",
  "Minimalist mountain logo at sunrise",
  "Cyberpunk Tokyo alley in the rain",
];

export function Imagine() {
  const [prompt, setPrompt] = useState(prompts[0]);
  const [seed, setSeed] = useState(0);

  return (
    <section id="imagine" className="relative py-32 px-6 overflow-hidden">
      <div className="absolute inset-0 bg-violet-gradient opacity-[0.06] blur-3xl" />
      <div className="relative mx-auto max-w-7xl">
        <div className="max-w-2xl">
          <div className="text-sm text-violet mb-3 flex items-center gap-2">
            <SymbolMark className="text-base" /> Imagine
          </div>
          <h2 className="text-4xl sm:text-5xl font-bold text-gradient">
            Create anything<br />you can describe.
          </h2>
          <p className="mt-5 text-muted-foreground text-lg">
            Imagine is Luna's built-in generation engine. Sketch ideas, brand concepts, illustrations,
            and photoreal scenes in a single conversation.
          </p>
        </div>

        <div className="mt-14 grid lg:grid-cols-[1.2fr_1fr] gap-8">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {gallery.map((g, i) => (
              <div
                key={g.label}
                className={`aspect-square rounded-2xl bg-gradient-to-br ${g.grad} relative overflow-hidden group cursor-pointer`}
                style={{ animationDelay: `${i * 0.05}s` }}
              >
                <div className="absolute inset-0 grid-bg opacity-20" />
                <div className="absolute inset-0 flex items-center justify-center text-3xl opacity-0 group-hover:opacity-90 transition">
                  <SymbolMark />
                </div>
                <div className="absolute bottom-2 left-2 text-[11px] font-medium glass rounded-full px-2 py-0.5">
                  {g.label}
                </div>
              </div>
            ))}
          </div>

          <div className="glass-strong rounded-3xl p-6 self-start">
            <div className="text-sm text-muted-foreground mb-3">Try a prompt</div>
            <div className="flex flex-wrap gap-2 mb-4">
              {prompts.map((p) => (
                <button
                  key={p}
                  onClick={() => { setPrompt(p); setSeed((s) => s + 1); }}
                  className={`text-xs rounded-full px-3 py-1.5 transition ${
                    prompt === p ? "bg-violet-gradient text-primary-foreground" : "glass hover:bg-secondary/50"
                  }`}
                >
                  {p.split(" ").slice(0, 3).join(" ")}…
                </button>
              ))}
            </div>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              className="w-full bg-secondary/50 rounded-2xl p-4 text-sm outline-none focus:ring-2 focus:ring-ring resize-none"
              rows={3}
            />
            <button
              onClick={() => setSeed((s) => s + 1)}
              className="mt-3 w-full rounded-full bg-violet-gradient text-primary-foreground font-medium py-3 glow hover:opacity-90 transition"
            >
              Generate
            </button>

            <div
              key={seed}
              className="mt-5 aspect-video rounded-2xl overflow-hidden relative animate-fade-up"
              style={{
                background: `conic-gradient(from ${seed * 47}deg at 50% 50%, oklch(0.7 0.25 ${(seed * 60) % 360}), oklch(0.5 0.22 ${(seed * 90 + 120) % 360}), oklch(0.3 0.18 ${(seed * 30 + 240) % 360}), oklch(0.7 0.25 ${(seed * 60) % 360}))`,
              }}
            >
              <div className="absolute inset-0 grid-bg opacity-20" />
              <div className="absolute bottom-3 left-3 glass rounded-full px-3 py-1 text-[11px] flex items-center gap-1.5">
                <SymbolMark className="text-sm" /> Generated by Imagine
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
